### ISSUE TITLE
Incompatibility with NixVIM checks

### ISSUE THREAD

**Issue by redyf** [IogaMaster/neocord#11]
### Description

Every time I run nix flake check on my custom nixvim config, it displays an error related to neocord. However the error only shows up in nix flake check, nix run or any other command work with no issues.

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

### OS information

NixOS 24.05 (Uakari)

### Steps to reproduce

1. Fetch neocord from the github repo as there's no package for it in nixpkgs (yet)
2. Require it in your neocord.nix with **require("neocord").setup()**
3. Call it in default.nix
4. Run nix flake check

### Logs

$ nix flake check
error: builder for '/nix/store/rl6byifrkh8mjf6aanvp4893vmvpzqrc-Neve.drv' failed with exit code 1;
       last 7 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > ERROR: [neocord] Failed to get socket information: ENOENT: no such file or directory: /build/discord-ipc-0
       > [neocord] Failed to connect to Discord: ENOENT
       For full logs, run 'nix log /nix/store/rl6byifrkh8mjf6aanvp4893vmvpzqrc-Neve.drv'.

**Comment by IogaMaster** [comment]
This was on NixVim's end, according to:

![image](https://github.com/IogaMaster/neocord/assets/67164465/7a4e642c-c1ef-4705-bc87-46f8b3d52bd9)
