### ISSUE TITLE
Stop showing "[neocord] Failed to connect to Discord: ENOENT" when Discord is not open or on blacklisted paths

### ISSUE THREAD

**Issue by Nanito111** [IogaMaster/neocord#14]
I don't have always Discord open, so it's annoying to see all the time "[neocord] Failed to connect to Discord: ENOENT" when I edit something in neovim.

It would be cool to have a timeout (configurable too) when trying to connect to Discord.
Another good improvement would be to not show that message on blacklisted paths.

**Comment by IogaMaster** [comment]
Should be fixed in 35ccf9330f3521a17ca2948856cc79d17a408a33
