### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by priyansu1001** [IogaMaster/neocord#16]
### Description

I installed the with Vim-plug , put it in my init.vim, did :PlugInstall.
Restarted discord, restarted neovim, still no rich presence in discord.
My game activity is also on
![image](https://github.com/IogaMaster/neocord/assets/85109515/ec5ab29d-3e6e-4fed-be3f-6cb4bd7b9861)

The error
![image](https://github.com/IogaMaster/neocord/assets/85109515/39c8d5b4-f90f-4df6-9152-d216ea5a89a9)

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### OS information

windows 11 22H2

### Steps to reproduce

I did this in my init.vim
![image](https://github.com/IogaMaster/neocord/assets/85109515/b462f9ac-2ed8-4546-820f-a4cf7af8e902)
did :PlugInstall
restarted neovim and discord

### Logs

Whenever I open my nvim, while discord is on
![image](https://github.com/IogaMaster/neocord/assets/85109515/91b91640-9355-40cf-9b47-22249a94c794)
and rich presence doesnt work.

**Comment by h4rldev** [comment]
Yeah, got the same issue on lazy.nvim

**Comment by Sarthak-Bhagat** [comment]
+1 facing the same issue with lazy.nvim with a clean install of nvchad

**Comment by IogaMaster** [comment]
@LRitzdorf You added the vimscript stuff, do you mind helping me fix this?

**Comment by LRitzdorf** [comment]
Sure! Although actually, this doesn't look like a vimscript-specific issue, at least to my eyes. Yes, the vimscript-oriented `setup_no_return()` function is called, but the error occurs inside of Neocord's own internals, which I've never touched.

The top-level error happens at [`lua/neocord/init.lua:283`](https://github.com/IogaMaster/neocord/blob/35ccf9330f3521a17ca2948856cc79d17a408a33/lua/neocord/init.lua#L2830) (in `neocord:authorize()`), and indicates that `response` is nil. `response` is provided by the `discord:authorize()` function, so my feeling is that this is an auth issue of some kind?

Also, just for context — that `setup_no_return()` function calls the normal `neocord.setup()` and discards its return value. There isn't anything special about it at all, and no way (that I can see) for it to introduce any new errors.

**Comment by priyansu1001** [comment]
Excuse me everyone, the issue doesnt pop up anymore, but rather now whenever I use my plugins (telescope or nerd-tree), discord detects my nvim presence and it works. But without using anything, just open nvim, discord doesnt detect my nvim presence. 
IS it normal? If yes, ok.
Orelse should I close this issue and make another?

**Comment by ozwaldorf** [comment]
Same issue using nixvim integration for neocord, and arRPC providing the RPC

**Comment by Err-G** [comment]
I was having the same issue. I messed a bit with [lua/neocord/init.lua:283](https://github.com/IogaMaster/neocord/blob/35ccf9330f3521a17ca2948856cc79d17a408a33/lua/neocord/init.lua#L2830) and you use the response only to print the username and nothing more, i get rid of the printing the user name like this:
```lua
self.log:info(string.format("Authorized with Discord")) -- for %s", response.data.user.username))
```
and it just worked, (I don't know all the consequences of doing this)

**Comment by IogaMaster** [comment]
Idk either, as the code is from the original project.

**Comment by Err-G** [comment]
> Idk either, as the code is from the original project.

I was having the same problem in the original project, but the original looks like unmaintained.

**Comment by IogaMaster** [comment]
Should be fixed with latest pr
