### ISSUE TITLE
Support calling `setup()` from Vimscript?

### ISSUE THREAD

**Issue by LRitzdorf** [IogaMaster/neocord#2]
Neovim supports calling Lua functions, using syntax like `call v:lua.require'neocord'.setup({})` (see [`v:lua-call`](https://neovim.io/doc/user/lua.html#v%3Alua-call)). This should provide a way for VimL init-script users to call neocord's `setup` function.

However, calling `setup` in this way currently throws an error:
```
Error detected while processing /home/XXX/.config/nvim/init.vim:         
line  X:
E5101: Cannot convert given lua type
```
This seems to be the result of `setup` [returning a Lua object reference](https://github.com/IogaMaster/neocord/blob/29a9f7c62ed907e3a6d0bdfbf989731d8ea2c155/lua/neocord/init.lua#L132C14-L132C14), which Neovim cannot convert back to a native VimL type.

While I realize that this plugin is written entirely in Lua (and therefore probably expects users' init scripts to also be in Lua), it would be nice if we had a version of the setup function which were compatible with this calling format (i.e. one that returned nil).

If this is in scope, I'd certainly be willing to PR it, though that should be pretty trivial.

**Comment by IogaMaster** [comment]
> If this is in scope, I'd certainly be willing to PR it, though that should be pretty trivial.

if you would be will I would love to have the pr!

**Comment by LRitzdorf** [comment]
Since #3 has been merged, this is now resolved. See the Readme for usage details!

**Comment by IogaMaster** [comment]
Thanks for your work! :heart:
