### ISSUE TITLE
Change name of RPC

### ISSUE THREAD

**Issue by tungstengmd** [IogaMaster/neocord#23]
**Is your feature request related to a problem? Please describe.**
Basically I have a Neovim config and I want to change the title of the RPC from Neovim to Nekovim.

**Describe the solution you'd like**
The ability to change the title.

**Comment by IogaMaster** [comment]
Currently discord uses the game of the application to set the name.

So you will need to create your own custom discord app. And point neocord to it, using the client_id setting.

All of the icons are loaded from the github page. So you will not need to upload any icons to the app.

**Comment by tungstengmd** [comment]
ah right
me and a friend already have our own fork of this for my own config currently

**Comment by IogaMaster** [comment]
Well feel free to pr your changes upstream if you make anything others might want

**Comment by tungstengmd** [comment]
i'll tell posaidon
