### ISSUE TITLE
difference from other DRiP plugins?

### ISSUE THREAD

**Issue by daUnknownCoder** [IogaMaster/neocord#31]
### Description

ok so i have used many rich presence plugins and always wanting for something simple and fast...

this is the OG guy: https://github.com/andweeb/presence.nvim, 
this guy took over the broken project: https://github.com/jiriks74/presence.nvim
this thing is also written in lua: https://github.com/pandasoli/nekovim

this is the one im using right now and it has too much customizability: https://github.com/vyfor/cord.nvim (this is written in rust)
so should i use neocord?

### Neovim version

```markdown
v0.10.0
```

### OS information

6.7.9-arch1-1 (Hyprland)

### Steps to reproduce

~ presence ~

### Logs

:hello world:

**Comment by arztareef** [comment]
cord.nvim is just better

**Comment by IogaMaster** [comment]
> cord.nvim is just better

Most likely, this is just a fork from presence.nvim to keep a pure lua DRiP. :wink:

**Comment by IogaMaster** [comment]
This just kinda slipped my notifs, this plugin is nothing special. If you want a pure lua discord presence then you should. But if you are not interested, cord.nvim is better and more actively maintained.
God bless!

**Comment by daUnknownCoder** [comment]
> This just kinda slipped my notifs, this plugin is nothing special. If you want a pure lua discord presence then you should. But if you are not interested, cord.nvim is better and more actively maintained. God bless!

i would love using a lua one if it gives me the customizability cuz for the rust one i have to install rust

**Comment by IogaMaster** [comment]
This one is fairly customizable, custom icons etc
