### ISSUE TITLE
git status error

### ISSUE THREAD

**Issue by i007c** [IogaMaster/neocord#8]
### Description

in git fugitive. in the status buffer im getting an error:
![image](https://github.com/IogaMaster/neocord/assets/64564512/457dde36-cd30-4c70-be79-35cb7b87a91c)

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### OS information

arch linux 6.6.10-arch1-1

### Steps to reproduce

just open the git fugitive status

### Logs

[neocord] Failed to set activity in Discord: Received error event - child "activity" fails because [child "assets" fails because [child
 "large_text" fails because ["large_text" length must be at least 2 characters long]]] (code 4000)

**Comment by IogaMaster** [comment]
What about the commit:
d5f51d466644fe3c62eda4c41e373ecdc299a367

**Comment by IogaMaster** [comment]
@i007c Does this now work?

**Comment by i007c** [comment]
nope. no change sir. same error i think
```
[neocord] Failed to set activity in Discord: Received error event - child "activity" fails because [child "assets" fails because [child
 "large_text" fails because ["large_text" length must be at least 2 characters long]]] (code 4000)
 ```

**Comment by IogaMaster** [comment]
I see, I will continue to investigate.

**Comment by i007c** [comment]
i found the issue.
in your `init.lua` file at line `709` `neocord:update_for_buffer`
you are getting the filename and project name

but the problem is that fugitive has a diffrent name. i found this on debug log

```
[neocord] Parsed filename / with no extension
[neocord] Getting project name for fugitive:///home/i007c/tmp/neocord/.git/...
[neocord] Failed to get project name (error code 1): bash: line 1: cd: fugitive:///home/i007c/tmp/neocord/.git/: No such file or directory
```

and for the one character filename. thats fine but discord doesnt allow that.
so you can check if the `large_text` is less then 2 char and just append some random char to it.

**Comment by IogaMaster** [comment]
I don't show the project for any git interface. I will patch out the issue of large_text length

**Comment by i007c** [comment]
no the problem is your get_filename function. it cant handle the fugitive URIs
